[application]
icon = ["ilogo.png"]

[web.app]

# HTML title tag content
title = "Codeor"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.codeor"
publisher = "Codeor"
resources = ["assets", "src", "target"]
icon = ["assets/logo.png"]